name: FirebaseDeployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Install Dependencies and Build
        env:
          VUE_APP_PRISMA_HTTPS: ${{secrets.PRISMA_HTTPS}}
          VUE_APP_PRISMA_WSS: ${{secrets.PRISMA_WSS}}
          VUE_APP_FIREBASE_API_KEY: ${{secrets.VUE_APP_FIREBASE_API_KEY}}
          VUE_APP_FIREBASE_AUTH_DOMAIN: ${{secrets.VUE_APP_FIREBASE_AUTH_DOMAIN}}
          VUE_APP_FIREBASE_DATABASE_URL: ${{secrets.VUE_APP_FIREBASE_DATABASE_URL}}
          VUE_APP_FIREBASE_PROJECT_ID: ${{secrets.VUE_APP_FIREBASE_PROJECT_ID}}
          VUE_APP_FIREBASE_STORAGE_BUCKET: ${{secrets.VUE_APP_FIREBASE_STORAGE_BUCKET}}
          VUE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.VUE_APP_FIREBASE_MESSAGING_SENDER_ID}}
          VUE_APP_FIREBASE_APP_ID: ${{secrets.VUE_APP_FIREBASE_APP_ID}}
          VUE_APP_FIREBASE_MEASUREMENT_ID: ${{secrets.VUE_APP_FIREBASE_MEASUREMENT_ID}}
        run: |
            cd app/
            npm ci
            npm run build
            cd ..
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
